### ISSUE TITLE
Events Page Search Button Fails to Filter Events by User Input

### ISSUE THREAD

**Issue by Jing27540** [Software-Engineering-2024-Group/BurnoutExtreme#44]
The search button on the Events page does not filter the events list based on user-entered keywords, resulting in irrelevant or unfiltered results.

![image](https://github.com/user-attachments/assets/1f9ed242-74c4-4d31-bf5e-ca80da5b75f5)

Steps to Reproduce:
	1.	Navigate to the Events page.
	2.	Enter a keyword in the search bar.
	3.	Click the search button.
	
Expected Behavior: The events list should display only events that match the entered keyword.
Actual Behavior: The search button does not filter the events list based on the keyword input.
Proposed Solution: Adjust the search functionality to filter events according to the user’s input keywords.

**Comment by SoundaryaKhanapur** [comment]
Yes, fixed it and merged to main
