### ISSUE TITLE
Edit Mode Remains Active After Removing an Item from Workout Plan

### ISSUE THREAD

**Issue by Jing27540** [Software-Engineering-2024-Group/BurnoutExtreme#45]
When an item is removed from the workout plan, edit mode remains active instead of switching to false as expected.

![image](https://github.com/user-attachments/assets/2290099e-4ea0-4f14-8502-6b660a6642b3)

Steps to Reproduce:
	1.	Open the workout plan in edit mode.
	2.	Remove an item from the plan.
	
Expected Behavior: After removing an item, edit mode should automatically turn off (set to false).
Actual Behavior: Edit mode remains active after item removal.
Proposed Solution: Ensure that the edit mode state changes to false upon item removal from the workout plan.

**Comment by mugdhaajoshi** [comment]
Closing as fixed and can keep for future enhancement.
