### ISSUE TITLE
Events Page Search Button Fails to Filter Events by User Input

### ISSUE THREAD

**Issue by Jing27540** [Software-Engineering-2024-Group/BurnoutExtreme#47]
The search button on the Events page does not filter the events list based on user-entered keywords, resulting in irrelevant or unfiltered results.
![image](https://github.com/user-attachments/assets/9ec7febb-615d-4746-8837-59576847ea55)

Steps to Reproduce:
	1.	Navigate to the Events page.
	2.	Enter a keyword in the search bar.
	3.	Click the search button.
	4. 
Expected Behavior: The events list should display only events that match the entered keyword.
Actual Behavior: The search button does not filter the events list based on the keyword input.
Proposed Solution: Adjust the search functionality to filter events according to the user’s input keywords.

**Comment by SoundaryaKhanapur** [comment]
It is resolved and merged to main branch
