### ISSUE TITLE
Unintended UI Style Change on FAQ Page

### ISSUE THREAD

**Issue by Jing27540** [Software-Engineering-2024-Group/BurnoutExtreme#48]
The FAQ page has unexpected styling changes that are inconsistent with the app’s overall theme.
![image](https://github.com/user-attachments/assets/417ffce2-36bd-4237-a3f3-a25b3918630c)

Expected Behavior: The FAQ page should match the app’s established theme and styling.
Observed Behavior: UI styling on the FAQ page differs from other sections.
Proposed Solution: Adjust styles to align with the overall app theme.

**Comment by SoundaryaKhanapur** [comment]
Updated the CSS
